# Generated by Django 4.2 on 2025-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodels",
            name="tax",
            field=models.DecimalField(decimal_places=0, default=0.09, max_digits=10),
        ),
    ]
