# Generated by Django 4.2 on 2025-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_ordermodels_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddressmodels",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
