# Generated by Django 4.2 on 2025-08-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
