# Generated by Django 4.2 on 2025-08-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodels',
            name='order',
        ),
    ]
